name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 10 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec tsc -v
      - run: pnpm exec tsc --noEmit
      - run: pnpm exec eslint . --ext .ts,.tsx
